# Generated by Django 4.0.4 on 2022-05-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
