# Generated by Django 4.0.4 on 2022-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_campaign_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='com',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='lin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
