# Generated by Django 4.0.4 on 2022-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_campaign_com_campaign_lin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='com',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='lin',
            field=models.TextField(default=None),
        ),
    ]
