# Generated by Django 4.0.4 on 2022-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_campaign_com_alter_campaign_lin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='com',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='lin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
